version: '4.2'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - ANNOUNCED_IP=127.0.0.1
    volumes:
      - ./backend:/app
    networks:
      - exam-network

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - exam-network

networks:
  exam-network:
    driver: bridge